### ISSUE TITLE
اصلاح مثال برای Version Control

### ISSUE THREAD

**Issue by mhmda-83** [sabajamalian/debugging-teams-fa#5]
![image](https://user-images.githubusercontent.com/46217391/126677589-baca2402-ff36-43e4-ba14-c16f501cc6ef.png)

مثالی که اینجا برای Version Control زده شده، مثال درستی نیست به این دلیل که Github در واقع یک ریموت سرور هست برای git و این گیته که یه ورژن کنترل محسوب میشه.

ضمنا دمتون خیلی گرم بابت ترجمه این کتاب ❤️

**Comment by sabajamalian** [comment]
Thank you! 
This will be corrected in the next release (PR attached). Please note that we currently do not have a timeline on when the next release will be out.
